// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4P38RkI36hPKE7917ROvStuHIOZcgmJU',
    appId: '1:298926531053:web:c6f5c1b8c25f22a740c7e4',
    messagingSenderId: '298926531053',
    projectId: 'litepay-123580',
    authDomain: 'litepay-123580.firebaseapp.com',
    storageBucket: 'litepay-123580.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sNoixj6QVKlHPDZSJRszVf4btvUVFWo',
    appId: '1:298926531053:android:6803d93e4b20cf1b40c7e4',
    messagingSenderId: '298926531053',
    projectId: 'litepay-123580',
    storageBucket: 'litepay-123580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPITqhrbp8O0H7HNp6wezNh4mDptSaaA',
    appId: '1:298926531053:ios:937955ccd1a60c4b40c7e4',
    messagingSenderId: '298926531053',
    projectId: 'litepay-123580',
    storageBucket: 'litepay-123580.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPITqhrbp8O0H7HNp6wezNh4mDptSaaA',
    appId: '1:298926531053:ios:73e82e5b877dd57440c7e4',
    messagingSenderId: '298926531053',
    projectId: 'litepay-123580',
    storageBucket: 'litepay-123580.appspot.com',
    iosBundleId: 'litepay.app',
  );
}
